version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
  target-branch: develop
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - "> 6.2.3, < 7"
  - dependency-name: fetch-mock
    versions:
    - "> 9.1.1, < 10"
  - dependency-name: file-saver
    versions:
    - "> 2.0.2, < 3"
  - dependency-name: geographiclib
    versions:
    - "> 1.50.0"
  - dependency-name: husky
    versions:
    - "> 4.2.3, < 5"
  - dependency-name: postcss-cli
    versions:
    - "> 7.1.0, < 8"
  - dependency-name: proj4
    versions:
    - "> 2.6.1, < 3"
  - dependency-name: rc-slider
    versions:
    - "> 9.2.2, < 10"
  - dependency-name: webpack-cli
    versions:
    - "> 3.3.10, < 4"
  - dependency-name: web-streams-polyfill
    versions:
    - "> 2.0.6"
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.10
    - 7.13.14
  - dependency-name: geckodriver
    versions:
    - 1.22.1
    - 1.22.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: ol-mapbox-style
    versions:
    - 6.3.0
    - 6.3.1
  - dependency-name: "@fortawesome/react-fontawesome"
    versions:
    - 0.1.13
  - dependency-name: jest-canvas-mock
    versions:
    - 2.3.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.1
